### ISSUE TITLE
[Idea Suggestion] Use CustomModelData nbt instead of card display names

### ISSUE THREAD

**Issue by sarhatabaot** [isaaclepes/TradingCardsResource#3]
**Describe your idea**
Use the custommodeldata available in my fork instead of relying on card titles.
This will allow the resource pack to work even if people changed their card titles. (i.e, different language or something other than [Card])

In general we use NBT data, see https://github.com/sarhatabaot/TradingCards/blob/master/tradingcards-api/src/main/java/net/tinetwork/tradingcards/api/utils/NbtUtils.java for all the info.

Aside from custommodeldata, we also store the card name, series, rarity, if it's shiny & if it's a card in nbt data.
On decks we store the deck number & if it's a deck.

**Additional context**
```yaml
cards:
  common:
    zombie:
      display-name: 'Zombie'
      series: 'default'
      type: 'Monster'
      has-shiny-version: true
      info: 'none'
      # if vault is enabled, how much this card is worth. set to 0 to not allow buying.
      # Unless specified we will use the prices from rarities.
      buy-price: 100.0
      sell-price: 50.0
      Custom-Model-Data: 3200001
...
```
